# This file is used to pin the rust toolchain to a specific nightly version.
# For more info, see: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
# We pin the nightly toolchain so we can have reproducible builds.
channel = "nightly-2023-09-01"

# Here we specifiy the additional targets for compiliation, the host target is by default included.
targets = ["wasm32-unknown-unknown"]
